-- name: CONSUMPTION_FORECAST_QUERY
SELECT
    om2.ID AS SECTION_ID,
    NAA.CUSTOMER_ACCOUNT_NO,
    TO_CHAR(TO_DATE(TO_CHAR(NAA.ENE_DATE), 'YYYYMMDD'), 'YYYY-MM-DD HH24:MI:SS') AS DAYS,
    WRD.TEMPERATURE,
    WRD.HUMIDITY,
    WRD.WIND_SPEED,
    WRD.HOLIDAY,
    WRD.HOLIDAY_NAME,
    NAA.KWH_IMP AS ACTUAL_CONSUMPTION
FROM
    mis_user.AMI_NETWORK_AREA_AGGREGATION NAA
INNER JOIN
    mis_user.WEATHER_RAW_DATA WRD
    ON TO_DATE(NAA.ENE_DATE, 'YYYYMMDD') = TRUNC(WRD.DAY)
INNER JOIN
    AMI_OFFICE_M aom ON NAA.OFF_ID = aom.ID
INNER JOIN
    COMMON_USER.OFFICE_MASTER om2 ON TO_CHAR(aom.OFFICE_CODE) = TO_CHAR(om2.OLD_UCODE)
WHERE
    TO_DATE(NAA.ENE_DATE, 'YYYYMMDD') BETWEEN TO_DATE('{start_date}', 'YYYY-MM-DD') AND TO_DATE('{end_date}', 'YYYY-MM-DD')
    AND aom.RECORD_STATUS = 1
    AND om2.RECORD_STATUS = 1
    AND om2.ID IN ({section_ids})

-- name: DAILY_DEMAND_FORECAST_QUERY
SELECT
    om2.ID AS SECTION_ID,
    NAA.CUSTOMER_ACCOUNT_NO,
    TO_CHAR(TO_DATE(TO_CHAR(NAA.ENE_DATE), 'YYYYMMDD'), 'YYYY-MM-DD HH24:MI:SS') AS DAYS,
    NAA.KWH_IMP AS ACTUAL_CONSUMPTION
FROM
    mis_user.AMI_NETWORK_AREA_AGGREGATION NAA
INNER JOIN
    AMI_OFFICE_M aom ON NAA.OFF_ID = aom.ID
INNER JOIN
    COMMON_USER.OFFICE_MASTER om2 ON TO_CHAR(aom.OFFICE_CODE) = TO_CHAR(om2.OLD_UCODE)
WHERE
    TO_DATE(NAA.ENE_DATE, 'YYYYMMDD') BETWEEN TO_DATE('{start_date}', 'YYYY-MM-DD') AND TO_DATE('{end_date}', 'YYYY-MM-DD')
    AND aom.RECORD_STATUS = 1
    AND om2.RECORD_STATUS = 1
    AND om2.ID IN ('{section_ids}')

-- name: CONSUMPTION_DEMAND_FORECAST_QUERY_SECTION
SELECT sum(BILL_UNITS) CONSUMPTION, BILLMONTH, BILLYEAR, OFFICE_ID as SECTION_ID FROM MIS_USER.BILL_STG_RAW_DATA 
WHERE 
    OFFICE_ID IN ('{section_ids}') 
    AND CURRENT_METER_STATUS != 'MD' AND BILL_MODE != '4X' AND defective_count < 10 AND ld_range < 4 AND bill_type NOT LIKE 'Comp%' 
    AND (BILLYEAR < '{year}' OR (BILLYEAR = '{year}' AND BILLMONTH <= '{month}')
) GROUP BY billmonth, billyear, office_id


-- name: CONSUMPTION_DEMAND_FORECAST_QUERY
SELECT sum(BILL_UNITS) CONSUMPTION, BILLMONTH, BILLYEAR, OFFICE_ID as SECTION_ID FROM MIS_USER.BILL_STG_RAW_DATA 
WHERE 
    OFFICE_ID IN ({section_ids}) 
    AND CURRENT_METER_STATUS != 'MD' AND BILL_MODE != '4X' AND defective_count < 10 AND ld_range < 4 AND bill_type NOT LIKE 'Comp%' 
    AND (BILLYEAR < '{year}' OR (BILLYEAR = '{year}' AND BILLMONTH <= '{month}')
) GROUP BY billmonth, billyear, office_id

-- name: WEATHER_MASTER_QUERY
SELECT WEATHER_DATE, LOCATION, REGION, TEMPERATURE, HUMIDITY, CLOUD, WIND, UV, RAIN_CHANCE, PRESSURE FROM MIS_USER.WEATHER_MASTER
WHERE 
    WEATHER_DATE <= LAST_DAY(TO_DATE('{year}' || '-' || '{month}' || '-01','YYYY-MM-DD'))

-- name: WEATHER_MASTER_FUTURE_DATES_QUERY
SELECT WEATHER_DATE, LOCATION, REGION, TEMPERATURE, HUMIDITY, CLOUD, WIND, UV, RAIN_CHANCE, PRESSURE FROM MIS_USER.WEATHER_MASTER
WHERE 
    WEATHER_DATE BETWEEN TO_DATE('{start_date}', 'YYYY-MM-DD') AND TO_DATE('{end_date}', 'YYYY-MM-DD')

-- name: NEW_CONNECTION_QUERY
SELECT
    NRD.OFFICE_ID  AS SECTION_ID,NRD.REGISTRATION_NO AS CUSTOMER_ACCOUNT_NO,NRD.PHASE,NRD.CONNECTED_LOAD,NRD.CATEGORY_ID,  
    trunc(nrd.REGISTERED_DATE) AS APPLICATION_DATE,
    TRUNC(NRD.ACTUAL_SERVICE_RELEASE_DATE) AS DAYS,
    TRUNC(NRD.ACTUAL_SERVICE_RELEASE_DATE) - TRUNC(NRD.REGISTERED_DATE) AS DAYS_TAKEN,
    WRD.TEMPERATURE,
    WRD.HUMIDITY,
    WRD.WIND_SPEED,
    WRD.HOLIDAY,
    TO_CHAR(NRD.ACTUAL_SERVICE_RELEASE_DATE, 'D') AS DAY_OF_WEEK,
    CASE 
        WHEN TO_CHAR(NRD.ACTUAL_SERVICE_RELEASE_DATE, 'D') IN ('1', '7') THEN 1
        ELSE 0
    END AS IS_WEEKEND
FROM
MIS_USER.NSC_DATA_ML nrd 
INNER JOIN
    mis_user.WEATHER_RAW_DATA WRD
ON
    TRUNC(NRD.ACTUAL_SERVICE_RELEASE_DATE) = TRUNC(WRD.DAY)
WHERE
    EXTRACT(YEAR FROM ACTUAL_SERVICE_RELEASE_DATE) BETWEEN 2021 AND  2025
	

-- name: OFFICD_ID
select 
	id 
from common_user.office_master 
where record_status=1 
and parentoffice_id='804-144'  
start with id ='804-144'  connect by prior id= parentoffice_id 

-- name: DIVISION_IDS
SELECT ID FROM COMMON_USER.OFFICE_MASTER om WHERE 
ID IN (
          SELECT ID
          FROM COMMON_USER.OFFICE_MASTER OMF
          WHERE RECORD_STATUS = 1
            START WITH ID = '{division_id}'
            CONNECT BY PRIOR ID = PARENTOFFICE_ID
      )
ORDER BY ID

-- name: SCHEDULE_TASKS
SELECT USE_CASE, SUBTASK_NAME, CRON_EXPR, OFFICE_ID,TO_CHAR(START_DATE,'YYYY-MM-DD'), TO_CHAR(END_DATE,'YYYY-MM-DD'),MONTH,YEAR,FILTER_TYPE, QUEUE_NAME,MODEL_NAME
FROM USECASE_SCHEDULES
WHERE IS_ACTIVE = 'Y'


-- name: FEATURE_WEATHER
SELECT 
    DAY,
    TEMPERATURE,
    HUMIDITY,
    WIND_SPEED,
    HOLIDAY
FROM WEATHER_RAW_DATA
WHERE DAY BETWEEN TO_DATE('{start_date}', 'YYYY-MM-DD') AND TO_DATE('{end_date}', 'YYYY-MM-DD')


-- name: SEGMENTATION_QUERY
SELECT csrd.CONSUMER_ID,
       bsrd.CAT_CODE,
       bsrd.OFFICE_ID as SECTION_ID,
       bsrd.BILL_UNITS,
       bsrd.CONSUMER_SUPPLY_TYPE,
       bsrd.LOAD_IN_KW,
       ROUND( bsrd.bill_units / NULLIF(bsrd.load_in_kw * (30 * 24), 0), 3 ) AS LOAD_FACTOR,
       ROUND( bsrd.bill_units / NULLIF( ( (bsrd.bill_units / NULLIF(bsrd.load_in_kw * (30 * 24), 0)) * (30 * 24) ), 0 ), 2 ) AS PEAK_DEMAND_KW,
       crd.BILLING_STATUS,
       crd.METER_TYPE,
       crd.METER_PHASE,
       bsrd.ENERGY_CHG,
       bsrd.FIXED_CHG,
       bsrd.ARREAR_TOTAL AS ARREARS,
       bsrd.SUBSIDY,
       bsrd.BILL_AMOUNT,
       csrd.AMOUNT_COLLECTED,
       bsrd.BILL_DUE_DATE,
       csrd.TIME_ID,
       ABS(csrd.TIME_ID - bsrd.BILL_DUE_DATE) AS PAYMENT_LAG_DAYS,
       CASE 
            WHEN csrd.AMOUNT_COLLECTED = 0 THEN 'Bad Debt Risk'
            WHEN (csrd.TIME_ID - bsrd.BILL_DUE_DATE) <= 0 THEN 'On-time'
            WHEN (csrd.TIME_ID - bsrd.BILL_DUE_DATE) BETWEEN 1 AND 30 THEN 'Delayed'
            WHEN (csrd.TIME_ID - bsrd.BILL_DUE_DATE) > 30 THEN 'Default Risk'
            ELSE 'Other'
       END AS PAYMENT_BEHAVIOR,
       ROUND(bsrd.subsidy / NULLIF(bsrd.bill_amount,0), 3) AS SUBSIDY_SHARE,
       ROUND(bsrd.arrear_total / NULLIF(bsrd.bill_amount,0), 3) AS ARREAR_RATIO,
       ROUND(csrd.amount_collected / NULLIF(bsrd.bill_amount,0), 3) AS COLLECTION_RATIO,
       bsrd.DATA_MONTH AS BILL_MONTH,
       bsrd.DATA_year AS BILL_YEAR
FROM mis_user.COLL_STG_RAW_DATA csrd 
JOIN mis_user.BILL_STG_RAW_DATA bsrd 
  ON bsrd.CONSUMER_ID = csrd.CONSUMER_ID
JOIN mis_user.CONSUMER_RAW_DATA crd  
  ON crd.CONSUMER_ID = bsrd.CONSUMER_ID  
WHERE 
    crd.DATA_MONTH='4'
    AND crd.DATA_year='2025' 
    AND bsrd.BILL_DUE_DATE IS NOT NULL
    --AND bsrd.OFFICE_ID IN ({section_ids})    
    AND bsrd.TIME_ID BETWEEN TO_DATE('{start_date}', 'YYYY-MM-DD') AND TO_DATE('{end_date}', 'YYYY-MM-DD')
    AND csrd.TIME_ID BETWEEN TO_DATE('{start_date}', 'YYYY-MM-DD') AND TO_DATE('{end_date}', 'YYYY-MM-DD')

-- name: REVENUE_FORECAST_QUERY_SECTION
SELECT 
    CSRD.OFFICE_ID           AS SECTION_ID, 
    SUM(CSRD.AMOUNT_COLLECTED)  AS COLLECTION,  
    CSRD.COLL_MONTH          AS REV_MONTH, 
    CSRD.COLL_YEAR           AS REV_YEAR
FROM MIS_USER.COLL_STG_RAW_DATA CSRD
WHERE CSRD.DATA_STATUS    = 1
    AND CSRD.CANCL_STATUS   = 'N'
    AND CSRD.IS_CHEQ_BOUNCED = 'N'
    AND CSRD.OFFICE_ID IN ('{section_ids}')
    AND (COLL_YEAR < '{year}' OR (COLL_YEAR = '{year}' AND COLL_MONTH <= '{month}'))
GROUP BY CSRD.OFFICE_ID, CSRD.COLL_MONTH, CSRD.COLL_YEAR
ORDER BY CSRD.OFFICE_ID, CSRD.COLL_YEAR, CSRD.COLL_MONTH